# -*- coding: utf-8 -*-
"""
================================================================================
 Ren'Py 注入器
================================================================================
 职责:
   1. 生成 game/tl/chinese/*.rpy 翻译文件
   2. 生成 .translator_cache.json 供纠错编辑器使用
================================================================================
"""

import os
import json
from engine.backup_manager import BackupManager
from engine.extractor.detector import TranslationProject


class RenPyInjector:
    """Ren'Py 翻译注入器"""

    CACHE_FILENAME = ".translator_cache.json"
    TL_DIR = "game/tl/chinese"

    def __init__(self):
        self._backup_mgr = None

    def inject(self, project: TranslationProject, apply_corrections: bool = False) -> dict:
        """
        生成 Ren'Py 翻译文件。

        参数:
            project: TranslationProject
            apply_corrections: 是否使用 approved_text
        返回:
            统计信息
        """
        if not project.entries:
            return {"error": "没有翻译条目可供注入"}

        self._backup_mgr = BackupManager(project.game_root)

        # 按 .rpy 文件分组
        file_groups = {}
        for entry in project.entries:
            fp = entry.file_path
            if fp not in file_groups:
                file_groups[fp] = []
            file_groups[fp].append(entry)

        # 创建 tl/chinese 目录
        tl_dir = os.path.join(project.game_root, self.TL_DIR)
        os.makedirs(tl_dir, exist_ok=True)

        injected_count = 0

        for rel_path, entries in file_groups.items():
            base_name = os.path.basename(rel_path)
            tl_file = os.path.join(tl_dir, base_name)

            lines = [
                "# -*- coding: utf-8 -*-",
                f"# Auto-generated translation for {rel_path}",
                "# Generated by Game Translator Tool",
                "",
                "translate chinese strings:",
                "",
            ]
            file_injected = 0

            for entry in entries:
                target = entry.approved_text if (apply_corrections and entry.approved_text) else entry.translated_text
                if not target or target.startswith("[翻译失败]"):
                    continue
                escaped_src = entry.source_text.replace('"', '\\"')
                escaped_tgt = target.replace('"', '\\"')
                lines.append(f'    old "{escaped_src}"')
                lines.append(f'    new "{escaped_tgt}"')
                lines.append("")
                file_injected += 1

            if file_injected > 0:
                try:
                    with open(tl_file, "w", encoding="utf-8") as f:
                        f.write("\n".join(lines))
                except IOError:
                    continue
                injected_count += file_injected

        # 生成缓存库
        cache_path = self._generate_cache(project)

        return {
            "injected": injected_count,
            "cache_path": os.path.relpath(cache_path, project.game_root),
        }

    def _generate_cache(self, project: TranslationProject) -> str:
        """生成 .translator_cache.json"""
        records = []
        for entry in project.entries:
            records.append({
                "file_path": entry.file_path,
                "key_path": entry.key_path,
                "source_text": entry.source_text,
                "translated_text": entry.translated_text,
                "approved_text": entry.approved_text or "",
                "is_approved": entry.is_approved,
            })

        cache = {
            "engine_type": project.engine_type,
            "game_root": project.game_root,
            "records": records,
            "total": len(records),
        }
        cache_path = os.path.join(project.game_root, self.CACHE_FILENAME)
        with open(cache_path, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
        return cache_path